"""Markdown and HTML reports. The HTML is one self-contained file with inline SVG charts."""

from __future__ import annotations

import html
import json

from goodput.analyze import CATEGORIES, WASTE, Summary, SLOResult
from goodput.experiments import Result, Sweep

LABELS = {"productive": "Productive", "checkpoint": "Checkpoint writes", "lost": "Lost work",
          "detect": "Detection", "wait": "Waiting for nodes", "restart": "Restart"}


def pct(x: float, digits: int = 1) -> str:
    return f"{x * 100:.{digits}f}%"


# --- analysis of one event log -------------------------------------------------------------------

def summary_text(s: Summary, slo_res: SLOResult | None = None, top: int = 5) -> str:
    lines = [f"Jobs: {s.jobs}, GPUs: {s.gpus}, wall-clock: {s.wall_hours:.1f} h, GPU-hours: {s.total_gpu_hours:,.0f}",
             f"Goodput: {pct(s.goodput)}",
             f"Interruptions: {s.interruptions}  MTBI: {_h(s.mtbi_hours)}  node MTBF (estimated): {_h(s.node_mtbf_hours)}",
             "", "Where the GPU-hours went:"]
    for c in CATEGORIES:
        lines.append(f"  {LABELS[c]:<18} {s.gpu_hours[c]:>12,.0f}  {pct(_share(s, c)):>6}")
    lines += ["", "Cost per interruption cause (lost work + detection + waiting + restart):"]
    for cause, d in sorted(s.by_cause.items(), key=lambda kv: -kv[1]["gpu_hours"]):
        lines.append(f"  {cause:<18} {d['count']:>4} x  {d['gpu_hours']:>10,.0f} GPU-h")
    if s.nodes:
        lines += ["", f"Nodes with the most interruptions (top {top}):"]
        lines += [f"  {n:<10} {k}" for n, k in s.nodes.most_common(top)]
    if slo_res:
        lines += ["", f"Goodput SLO {pct(slo_res.target, 0)} per {slo_res.window_hours:g} h window: "
                      f"met in {slo_res.met} of {len(slo_res.rows)}"]
        for r in slo_res.rows:
            lines.append(f"  {r['start']:%Y-%m-%d} {pct(r['goodput']):>6}  budget burn {pct(r['budget_burn'], 0):>5}  "
                         f"{r['interruptions']:>3} interruptions  top waste: {r['top_waste']}")
    return "\n".join(lines)


def summary_json(s: Summary, slo_res: SLOResult | None = None) -> str:
    d = {"jobs": s.jobs, "gpus": s.gpus, "wall_hours": round(s.wall_hours, 3), "goodput": round(s.goodput, 5),
         "interruptions": s.interruptions, "mtbi_hours": _r(s.mtbi_hours), "node_mtbf_hours": _r(s.node_mtbf_hours),
         "gpu_hours": {c: round(v, 1) for c, v in s.gpu_hours.items()},
         "by_cause": {k: {"count": v["count"], "gpu_hours": round(v["gpu_hours"], 1)} for k, v in s.by_cause.items()},
         "top_nodes": s.nodes.most_common(10)}
    if slo_res:
        d["slo"] = {"target": slo_res.target, "window_hours": slo_res.window_hours, "met": slo_res.met,
                    "windows": [{**r, "start": r["start"].isoformat(), "end": r["end"].isoformat(),
                                 "goodput": round(r["goodput"], 5), "budget_burn": round(r["budget_burn"], 4)}
                                for r in slo_res.rows]}
    return json.dumps(d, indent=2)


# --- experiments ---------------------------------------------------------------------------------

def results_markdown(results: list[Result], sw: Sweep) -> str:
    base = results[0].mean
    out = [f"<!-- generated by `goodput report`: {results[0].seeds} seeds per scenario, "
           f"{results[0].scenario.days:g} days each. Do not edit by hand; CI checks it is up to date. -->", "",
           "### Scenarios", "",
           "| Scenario | Goodput (mean) | p10–p90 | vs baseline | Interruptions / run | MTBI | Biggest waste |",
           "|---|---|---|---|---|---|---|"]
    for r in results:
        waste = max(WASTE, key=lambda c: r.shares[c])
        out.append(f"| {r.scenario.name} | {pct(r.mean)} | {pct(r.p10)}–{pct(r.p90)} | {(r.mean - base) * 100:+.1f} pp | "
                   f"{r.interruptions:.1f} | {r.mtbi_hours:.1f} h | {LABELS[waste]} ({pct(r.shares[waste])}) |")
    out += ["", "### Where the GPU-hours went (mean share)", "",
            "| Scenario | " + " | ".join(LABELS[c] for c in CATEGORIES) + " |",
            "|---|" + "---|" * len(CATEGORIES)]
    for r in results:
        out.append(f"| {r.scenario.name} | " + " | ".join(pct(r.shares[c]) for c in CATEGORIES) + " |")
    s = sw.scenario
    out += ["", f"### Checkpoint interval sweep ({s.name})", "",
            f"Job MTBI {s.nominal_mtbi_hours():.1f} h, checkpoint write {s.checkpoint_minutes:g} min. "
            f"Young: {sw.young_minutes:.0f} min, Daly: {sw.daly_minutes:.0f} min "
            f"(simulated goodput at Daly's interval: {pct(sw.daly_simulated)}). "
            f"Best interval in the sweep: {sw.best.interval_minutes:g} min ({pct(sw.best.simulated)}).", "",
            "| Interval | Simulated goodput | p10–p90 | First-order model |", "|---|---|---|---|"]
    for p in sw.points:
        out.append(f"| {p.interval_minutes:g} min | {pct(p.simulated)} | {pct(p.p10)}–{pct(p.p90)} | {pct(p.model)} |")
    return "\n".join(out) + "\n"


CSS = """
:root{--surface:#fcfcfb;--panel:#ffffff;--text:#0b0b0b;--text2:#52514e;--muted:#8a8984;--rule:#e4e3df;
--series:#2a78d6;--accent:#eb6834;color-scheme:light}
@media (prefers-color-scheme:dark){:root{--surface:#1a1a19;--panel:#222221;--text:#ffffff;--text2:#c3c2b7;
--muted:#8f8e86;--rule:#3a3a37;--series:#3987e5;--accent:#d95926;color-scheme:dark}}
*{box-sizing:border-box}body{margin:0;background:var(--surface);color:var(--text);
font:15px/1.5 system-ui,-apple-system,"Segoe UI",sans-serif}
main{max-width:1000px;margin:0 auto;padding:24px 16px 48px}h1{font-size:24px;margin:0 0 4px}
h2{font-size:18px;margin:36px 0 8px}p{color:var(--text2);margin:4px 0 12px}
.tiles{display:grid;grid-template-columns:repeat(auto-fit,minmax(170px,1fr));gap:12px;margin:20px 0}
.tile{background:var(--panel);border:1px solid var(--rule);border-radius:8px;padding:12px 14px}
.tile b{display:block;font-size:26px;font-variant-numeric:tabular-nums}.tile span{color:var(--text2);font-size:13px}
.wrap{overflow-x:auto}table{border-collapse:collapse;width:100%;font-variant-numeric:tabular-nums;font-size:14px}
th,td{text-align:right;padding:6px 8px;border-bottom:1px solid var(--rule);white-space:nowrap}
th:first-child,td:first-child{text-align:left}th{color:var(--text2);font-weight:600}
svg{width:100%;height:auto;display:block}svg text{fill:var(--text2);font-size:12px}
.grid{stroke:var(--rule)}.bar{fill:var(--series)}.bar:hover,.dot:hover{opacity:.8}.line{stroke:var(--series);fill:none;stroke-width:2}
.model{stroke:var(--muted);fill:none;stroke-width:2;stroke-dasharray:4 4}.dot{fill:var(--series);stroke:var(--panel);stroke-width:2}
.mark{stroke:var(--accent);stroke-width:2;stroke-dasharray:2 3}.band{fill:var(--series);opacity:.15}
.legend{display:flex;gap:18px;color:var(--text2);font-size:13px;margin:6px 0}.legend i{display:inline-block;width:18px;height:0;
border-top:2px solid var(--series);vertical-align:middle;margin-right:6px}.legend i.m{border-top:2px dashed var(--muted)}
.legend i.d{border-top:2px dotted var(--accent)}
"""


def results_html(results: list[Result], sw: Sweep, detail: Summary | None = None, slo_res: SLOResult | None = None) -> str:
    base = results[0]
    e = html.escape
    tiles = [(pct(base.mean), f"goodput, {e(base.scenario.name)}"),
             (f"{base.mtbi_hours:.1f} h", "mean time between interruptions"),
             (f"{sw.daly_minutes:.0f} min", "Daly checkpoint interval"),
             (pct(max(r.mean for r in results)), "best scenario")]
    parts = [f"<title>GPU goodput report</title><style>{CSS}</style><main>",
             "<h1>GPU goodput report</h1>",
             f"<p>Simulated {base.scenario.days:g}-day runs of a {base.scenario.job_nodes * base.scenario.gpus_per_node:,}-GPU "
             f"training job, {base.seeds} seeds per scenario. Lab assumptions, not measurements of a real cluster.</p>",
             '<div class="tiles">' + "".join(f'<div class="tile"><b>{v}</b><span>{k}</span></div>' for v, k in tiles) + "</div>",
             "<h2>Goodput by scenario</h2><p>Mean goodput over all seeds; the line on each bar spans p10–p90.</p>",
             _bars(results),
             '<div class="wrap"><table><tr><th>Scenario</th>' + "".join(f"<th>{LABELS[c]}</th>" for c in CATEGORIES) + "</tr>"]
    for r in results:
        parts.append(f"<tr><td>{e(r.scenario.name)}</td>" + "".join(f"<td>{pct(r.shares[c])}</td>" for c in CATEGORIES) + "</tr>")
    parts.append("</table></div>")
    parts += [f"<h2>Checkpoint interval ({e(sw.scenario.name)})</h2>",
              f"<p>Goodput against the time between checkpoints. Too often and checkpoint writes dominate; too rarely and each "
              f"interruption throws away more work. Daly's formula gives {sw.daly_minutes:.0f} min.</p>",
              '<div class="legend"><span><i></i>simulated (mean, band p10–p90)</span><span><i class="m"></i>first-order model</span>'
              '<span><i class="d"></i>Daly interval</span></div>', _sweep_chart(sw)]
    parts.append('<div class="wrap"><table><tr><th>Interval</th><th>Simulated</th><th>p10–p90</th><th>Model</th></tr>')
    for p in sw.points:
        parts.append(f"<tr><td>{p.interval_minutes:g} min</td><td>{pct(p.simulated)}</td>"
                     f"<td>{pct(p.p10)}–{pct(p.p90)}</td><td>{pct(p.model)}</td></tr>")
    parts.append("</table></div>")
    if detail:
        parts += [f"<h2>One run in detail ({e(base.scenario.name)}, seed 1)</h2>",
                  '<div class="wrap"><table><tr><th>Cause</th><th>Interruptions</th><th>GPU-hours lost</th></tr>']
        for cause, d in sorted(detail.by_cause.items(), key=lambda kv: -kv[1]["gpu_hours"]):
            parts.append(f"<tr><td>{e(cause)}</td><td>{d['count']}</td><td>{d['gpu_hours']:,.0f}</td></tr>")
        parts.append("</table></div>")
    if slo_res:
        parts += [f"<h2>Goodput SLO {pct(slo_res.target, 0)} per {slo_res.window_hours:g} h</h2>",
                  f"<p>Met in {slo_res.met} of {len(slo_res.rows)} windows. Budget burn above 100% means the window "
                  "used more unproductive GPU-hours than the SLO allows.</p>",
                  '<div class="wrap"><table><tr><th>Window</th><th>Goodput</th><th>Budget burn</th><th>Interruptions</th><th>Top waste</th></tr>']
        for r in slo_res.rows:
            parts.append(f"<tr><td>{r['start']:%Y-%m-%d}</td><td>{pct(r['goodput'])}</td><td>{pct(r['budget_burn'], 0)}</td>"
                         f"<td>{r['interruptions']}</td><td>{e(LABELS.get(r['top_waste'], r['top_waste']))}</td></tr>")
        parts.append("</table></div>")
    parts.append("</main>")
    return "<!doctype html><html lang=\"en\"><head><meta charset=\"utf-8\"><meta name=\"viewport\" " \
           "content=\"width=device-width,initial-scale=1\">" + "".join(parts[:1]) + "</head><body>" + "".join(parts[1:]) + "</body></html>\n"


def _bars(results: list[Result]) -> str:
    w, row, left, right = 760, 34, 170, 60
    h = row * len(results) + 30
    x = lambda v: left + v * (w - left - right)
    s = [f'<svg viewBox="0 0 {w} {h}" role="img" aria-label="Goodput by scenario">']
    for v in (0, .25, .5, .75, 1):
        s.append(f'<line class="grid" x1="{x(v):.1f}" x2="{x(v):.1f}" y1="0" y2="{h - 22}"/>'
                 f'<text x="{x(v):.1f}" y="{h - 6}" text-anchor="middle">{v * 100:.0f}%</text>')
    for i, r in enumerate(results):
        y = i * row + 6
        name = html.escape(r.scenario.name)
        s.append(f'<text x="{left - 10}" y="{y + 15}" text-anchor="end">{name}</text>'
                 f'<rect class="bar" x="{left}" y="{y + 2}" width="{max(x(r.mean) - left, 1):.1f}" height="18" rx="4">'
                 f'<title>{name}: {pct(r.mean)} (p10 {pct(r.p10)}, p90 {pct(r.p90)})</title></rect>'
                 f'<line stroke="currentColor" style="color:var(--text)" x1="{x(r.p10):.1f}" x2="{x(r.p90):.1f}" '
                 f'y1="{y + 11}" y2="{y + 11}" stroke-width="1.5"/>'
                 f'<text x="{max(x(r.mean), x(r.p90)) + 8:.1f}" y="{y + 15}">{pct(r.mean)}</text>')
    return "".join(s) + "</svg>"


def _sweep_chart(sw: Sweep) -> str:
    w, h, l, r, t, b = 760, 310, 52, 20, 12, 44
    xs = [p.interval_minutes for p in sw.points]
    lo = min(min(p.p10 for p in sw.points), min(p.model for p in sw.points))
    hi = max(max(p.p90 for p in sw.points), max(p.model for p in sw.points))
    lo, hi = max(0.0, (int(lo * 20)) / 20), min(1.0, (int(hi * 20) + 1) / 20)
    X = lambda m: l + (m - xs[0]) / (xs[-1] - xs[0]) * (w - l - r)
    Y = lambda v: t + (hi - v) / (hi - lo) * (h - t - b)
    s = [f'<svg viewBox="0 0 {w} {h}" role="img" aria-label="Goodput against checkpoint interval">']
    v = lo
    while v <= hi + 1e-9:
        s.append(f'<line class="grid" x1="{l}" x2="{w - r}" y1="{Y(v):.1f}" y2="{Y(v):.1f}"/>'
                 f'<text x="{l - 8}" y="{Y(v) + 4:.1f}" text-anchor="end">{v * 100:.0f}%</text>')
        v += 0.05
    last = -1e9
    for m in xs:  # skip tick labels that would collide with the previous one
        if X(m) - last >= 34:
            s.append(f'<text x="{X(m):.1f}" y="{h - 22}" text-anchor="middle">{m:g}</text>')
            last = X(m)
    s.append(f'<text x="{(l + w - r) / 2:.0f}" y="{h - 1}" text-anchor="middle">minutes between checkpoints</text>')
    band = " ".join(f"{X(p.interval_minutes):.1f},{Y(p.p90):.1f}" for p in sw.points) + " " + \
        " ".join(f"{X(p.interval_minutes):.1f},{Y(p.p10):.1f}" for p in reversed(sw.points))
    s.append(f'<polygon class="band" points="{band}"/>')
    s.append('<polyline class="model" points="' + " ".join(f"{X(p.interval_minutes):.1f},{Y(p.model):.1f}" for p in sw.points) + '"/>')
    s.append('<polyline class="line" points="' + " ".join(f"{X(p.interval_minutes):.1f},{Y(p.simulated):.1f}" for p in sw.points) + '"/>')
    if xs[0] <= sw.daly_minutes <= xs[-1]:
        s.append(f'<line class="mark" x1="{X(sw.daly_minutes):.1f}" x2="{X(sw.daly_minutes):.1f}" y1="{t}" y2="{h - b}"/>'
                 f'<text x="{X(sw.daly_minutes) + 6:.1f}" y="{t + 12}">Daly {sw.daly_minutes:.0f} min</text>')
    for p in sw.points:
        s.append(f'<circle class="dot" cx="{X(p.interval_minutes):.1f}" cy="{Y(p.simulated):.1f}" r="5">'
                 f'<title>{p.interval_minutes:g} min: simulated {pct(p.simulated)}, model {pct(p.model)}</title></circle>')
    return "".join(s) + "</svg>"


def _share(s: Summary, c: str) -> float:
    return s.gpu_hours[c] / s.total_gpu_hours if s.total_gpu_hours else 0.0


def _h(v: float | None) -> str:
    return f"{v:.1f} h" if v is not None else "n/a"


def _r(v: float | None):
    return round(v, 3) if v is not None else None
